[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "armenian-budget-tools"
version = "0.5.0"
description = "Armenian Budget Tools: parse and validate Armenian state budget datasets"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pandas",
  "openpyxl",
  "numpy",
  "tqdm",
  "xlrd",
  "colorlog",
  "PyYAML",
  "httpx",
  "rapidfuzz",
  "requests",
  "beautifulsoup4"
]

[project.scripts]
armenian-budget = "armenian_budget.interfaces.cli.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "jupyter",
  "ruff"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["armenian_budget*"]
